Repository maik-henrique/DH-Projeto-Integrador, pull requests merged in 2022-04, with the labels that each got.

#18 Feature/PL-10
  src/main/java/br/com/meli/dhprojetointegrador/controller/OrderController.java
  src/main/java/br/com/meli/dhprojetointegrador/entity/CartProduct.java
  src/main/java/br/com/meli/dhprojetointegrador/repository/ICartProductRepository.java
  src/main/java/br/com/meli/dhprojetointegrador/service/CartProductService.java
Labels: in progress

#21 feature: return all products
  src/main/java/br/com/meli/dhprojetointegrador/controller/OrderController.java
  src/main/java/br/com/meli/dhprojetointegrador/controller/ProductController.java
  src/main/java/br/com/meli/dhprojetointegrador/entity/Product.java
  src/main/java/br/com/meli/dhprojetointegrador/repository/ProductRepository.java
  src/main/java/br/com/meli/dhprojetointegrador/service/ProductService.java
Labels: in progress

#22 Fix/ PL-10
  src/main/java/br/com/meli/dhprojetointegrador/controller/OrderController.java
  src/main/java/br/com/meli/dhprojetointegrador/entity/CartProduct.java
  src/main/java/br/com/meli/dhprojetointegrador/enums/CategoryEnum.java
  src/main/java/br/com/meli/dhprojetointegrador/enums/StatusEnum.java
  src/main/java/br/com/meli/dhprojetointegrador/repository/CartProductRepository.java
  src/main/java/br/com/meli/dhprojetointegrador/service/CartProductService.java
Labels: code review

#24 Feature/pi 6 resolve conflicts on local branch
  src/main/java/br/com/meli/dhprojetointegrador/controller/ProductController.java
Labels: resolve conflicts

#41 add class ProductDto
  src/main/java/br/com/meli/dhprojetointegrador/controller/ProductController.java
  src/main/java/br/com/meli/dhprojetointegrador/dto/response/ProductResponseDto.java
  src/main/java/br/com/meli/dhprojetointegrador/service/ProductService.java
  src/test/java/br/com/meli/dhprojetointegrador/integration/ProductControllerTests.java
Labels: enhancement

#51 Feature/PI-10 - Testes
  src/main/java/br/com/meli/dhprojetointegrador/controller/OrderController.java
  src/main/java/br/com/meli/dhprojetointegrador/service/CartProductService.java
  src/test/java/br/com/meli/dhprojetointegrador/integration/OrderControllerTests.java
  src/test/java/br/com/meli/dhprojetointegrador/unit/service/CartProductServiceTest.java
  src/test/java/br/com/meli/dhprojetointegrador/unit/util/BuyerCreator.java
  src/test/java/br/com/meli/dhprojetointegrador/unit/util/CardProductCreator.java
  src/test/java/br/com/meli/dhprojetointegrador/unit/util/PurchaseOrderCreator.java
Labels: code review
